### ISSUE TITLE
MMvec comparision group and direction problem, plus Q2 value meaning

### ISSUE THREAD

**Issue by liuhuoz** [knightlab-analyses/mycobiome#2]
1. In the part of **MMvec per subset** in **1.0-genus-MMvec-run.ipynb** file

>
    tables_order = {
                    'bacteria-fungi':[table_one_tmp, table_two_tmp],
                    'fungi-bacteria':[table_two_tmp, table_one_tmp],
                    **'immune-bacteria':[table_three_tmp, table_one_tmp],**
                    'immune-fungi':[table_three_tmp, table_two_tmp],
                    **'bacteria-immune':[table_three_tmp, table_one_tmp],**
                    'fungi-immune':[table_two_tmp, table_three_tmp]
                   }

both 'Immune-bacteria' and 'bacteria-immune' groups are table_three_tmp pairing to table_one_tmp.
So is it a typo or running MMvec don't need the directional info?

2. Further, I want to ask question about the directional cooccurrence result.
Does the cooccurrence analysis show the directional effect from 1st compoent to the 2nd compoent?
For exmaple, in immune-fungi pair results, it displaies how immune cell affect the distribution of fungi. And reversely, the fungi-immune tells how the fungi affect immune cell.
Or just the both results are equal, and show some of compoents are co-exist based on a pattern, maybe B cell with Penicillium in some samples, and CD4 T cell with Fusarium in other samples, for instance.
I were confused because of the simliar heatmap patterns between the paired group. But when running MMvec, it actually need both directional pair. And in the original MMvec, the 1st componet means microbiom, and 2nd is metabolites. So I guess it has a direction between the 1st and 2nd componet.

3. One more little question, does a larger q2 value means a better model fitted? Or when the values larger than 0, all the models are acceptable and don't need to care the q2 values between models?

**Comment by cameronmartino** [comment]
Hi @liuhuoz,

1. Yes, that is a typo but luckily neither of those results were used in any downstream analysis or results.

2. I do not fully understand what is being asked here. So I will restate what I think was being asked which is "Does the table order matter and if so how/why?".  Yes, the table order into MMvec matters. MMvec (paper is [here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6884698/)) will estimate the conditional probabilities of observing a feature in the second input table (i.e. metabolites in the MMvec paper) given the input of each feature in the first table (i.e. microbes in the MMvec paper). In your example, this would mean estimating the conditional probability of seeing immune cell X given seeing fungi Y or the opposite fungi Y vs. immune cell X. 

3. Above zero is acceptable but the larger the value the better the model.

**Comment by liuhuoz** [comment]
> 

Thank you for your answers.
Now I know I confused the concepts of the conditional probabilities with co-existance probabilities.
